### ISSUE TITLE
About the HE_transcripts.csv file

### ISSUE THREAD

**Issue by DDDoGGie** [Roshan1992/RedeHist#1]
Hi, may I ask where can I got the **HE_transcripts.csv** file or how the image coordinates in the file were generated?

**Comment by Roshan1992** [comment]
Hi,

You can donwload the "transcripts_HE.csv" file from https://drive.google.com/file/d/1Y93zWhKSbLqNg31i-pwlew7-nQNHOJIJ

The coordinates refer to either transcript coordinates (imaging-based) or spot transcripts (sequencing-based), which are provided directly by ST platforms. Here, I downloaded the original transcript coordinates from the 10X human breast cancer Xenium dataset and manually aligned these coordinates with the corresponding H&E image.

**Comment by DDDoGGie** [comment]
Thanks very much for your help!
